export const CONFIGURATION_REDUCER_ACTION_TYPES = {
    SET_CONFIG_VALUE: "SET_CONFIG_VALUE",
    SET_CURRENT_SELECTED_DOMAIN: "SET_CURRENT_SELECTED_DOMAIN",
    SET_DEFAULT_CONFIG_VALUE: "SET_DEFAULT_CONFIG_VALUE",
  } as const;
  
  export type ConfigurationActionTypes =
    typeof CONFIGURATION_REDUCER_ACTION_TYPES[keyof typeof CONFIGURATION_REDUCER_ACTION_TYPES];
  